--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/stephen-mc-pl/libChunkLoader
branches:
- master
- "4.0"
projects:
  libChunkLoader:
    path: ""
    model: virion
    type: library
...
